### PR TITLE
add kanku to development

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by oskapt** [comment]
Is this a SUSE project? I see that it's included in openSUSE, but everything you've linked to makes it look like a personal project.

**Comment by aplanas** [comment]
AFAIK is used in OBS to orchestrate the VMs. Is an openSUSE project, maybe should be moved to the openSUSE github domain.

**Comment by lrupp** [comment]
It would not be possible for my team to run [OBS](https://build.opensuse.org/) and IBS without kanku. We are fixing OBS bugs found by kanku testing and we also use kanku to setup development environments for our branches. M0ses uses some of his working time to enhance kanku. So I see it clearly as a SUSE supported project.

Let me clarify with M0ses, if moving it under the openSUSE (or SUSE) umbrella makes sense, but it's clearly something that should be marked as SUSE project.

**Comment by oskapt** [comment]
Ok - I'll merge it. If the repo URL changes in the future, please open a new PR for the change.

**Pull request merged**
