### PR TITLE
Update trento.yaml

### PR DESCRIPTION
**Pull request by stefanotorresi**

### CODE REVIEW

**Comment by oskapt** [comment]
Hi. Can you alter the description or change it back to what it was? Your claim that it "improves upon the life" is subjective. Does it make coffee? Clean my house? Babysit my kids while I go to the store? How do you know that it improves on my life? What it my life is perfect? Do I not need to use your application if it is?

These descriptions are to explain what the project _does_ in clear terminology. The previous description came from the GitHub repo About section and is irrefutable. It says the project does X, and if it does X, then it's correct. If I use your software and it doesn't improve my life, has SUSE lied to me?

**Comment by stefanotorresi** [comment]
That's exactly how we describe the project, @oskapt, and the phrasing is very deliberate.
Is this site supposed to be prescriptive in how the various projects want to present themselves? What would be next? Would you reject the website url if it presented some content you didn't like? :)

**Comment by stefanotorresi** [comment]
I guess I just have to comply to your request, even if this means the list on this site won't be up-to-date with the upstream, but after all this is not a hill I'm gonna die on. ;)

**Comment by oskapt** [comment]
I'm not going to tell you how to do development on your project, but as a member of the Product Marketing Team, I do reserve the right to adjust the message to resonate better. I've renamed projects, changed their messaging, changed their URLs, and done whatever we need to do to make them as successful as possible when presented to other people. That's my job.

The purpose of marketing is to get people to use your project. After that, you're responsible for making sure the project meets their actual needs. This site exists to show people what SUSE is building. That's marketing. You can say whatever you want in your repo, and I probably won't ask you to change it until the project picks up enough traction that we start showcasing it.

**Pull request merged**
