### PR TITLE
Added kiwi project to the list

### PR DESCRIPTION
**Pull request by schaefi**
We would like to add the kiwi project to the list of
opensource projects lead by SUSE.

### CODE REVIEW

**Comment by schaefi** [comment]
Hi, thanks for looking into this project. If possible it would be great to become a featured project. As the instructions in the README said this should not be done by the author but by the PM team, I kindly ask about it here.

Thanks

**Review by Conan-Kudo — APPROVED** [review]

**Comment by oskapt** [comment]
> If possible it would be great to become a featured project.

Hi! We're still working out the criteria for what gets featured and when. Right now we plan to feature all the projects being showcased in keynotes at SUSECON and KubeCon. Is this project in either of those events?

**Comment by schaefi** [comment]
I assume at SUSECON or KubeCon the keynotes will cover SUSE's new inventions and achievements. The kiwi projects exists for some time and got showcased at the time it was new. Thus I expect it will not get direct attention.

One aspect I think is worth mentioning is that any project in SUSE that has something to do with an appliance build is created by kiwi. This also includes any base container, SLE Micro, the k3OS project, the Public-Cloud offering, the initiative of SUSE in the embedded market, and a lot more in and outside SUSE...

Maybe the scope of projects also helps to work out the criteria list.

Thanks much

**Comment by sysrich** [comment]
> > If possible it would be great to become a featured project.
> 
> Hi! We're still working out the criteria for what gets featured and when. Right now we plan to feature all the projects being showcased in keynotes at SUSECON and KubeCon. Is this project in either of those events?

One problem with this philosophy is that it pretty much rules out every single "not-Rancher" project in the SUSE portfolio.

This is because SUSE's typical go to market approach being to create a Product separate from the open source projects they are based on. That Product typically has a different name and separate EULA specific for that Product, separate from the license of the Open Source projects it's based on.

It impacts projects like kiwi here, which I could see being worthy of featuring, but also projects like openSUSE MicroOS, which are the direct upstream of major keynote-featured Products like SLE Micro, but SLE Micro isn't distributed as an open source project..

Maybe a better approach would be to feature projects that are 'part of' products being keynoted instead?

**Comment by oskapt** [comment]
All I know is that for now, we're featuring the stuff being talked about at SUSECON and KubeCon. This isn't a Rancher-focused view, and many of those projects have nothing to do with Rancher. They're E&I projects across the board.

During downtime between shows we can adjust featured content to correspond with campaigns - people come to the site looking for one thing, and they find a complementary project sitting next to it. We can rotate them on some timeline - I'm flexible. It's just not a problem we need to solve until after SUSECON.

It would be great to have MicroOS listed here. The more things we have, the more "sets" we can come up with to feature. "All operating systems," or "Everything for SAP" or whatever.

**Comment by fcrozat** [comment]
Kiwi was added by another PR, you should close this one.

**Pull request closed without merging**
